# Generated by Django 4.2.30 on 2026-07-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("early_fives", models.PositiveIntegerField(default=0)),
                ("top_lines", models.PositiveIntegerField(default=0)),
                ("middle_lines", models.PositiveIntegerField(default=0)),
                ("bottom_lines", models.PositiveIntegerField(default=0)),
                ("four_corners", models.PositiveIntegerField(default=0)),
                ("full_houses", models.PositiveIntegerField(default=0)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="accounts.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.IntegerField()),
                ("room_id", models.CharField(max_length=6)),
                ("points_earned", models.IntegerField(default=0)),
                ("is_host", models.BooleanField(default=False)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_histories",
                        to="accounts.player",
                    ),
                ),
            ],
        ),
    ]
