# Generated by Django 4.2.30 on 2026-07-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(db_index=True, max_length=6, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOBBY", "Lobby"),
                            ("PLAYING", "Playing"),
                            ("FINISHED", "Finished"),
                        ],
                        default="LOBBY",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_rooms",
                        to="accounts.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_online", models.BooleanField(default=True)),
                ("is_host", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_memberships",
                        to="accounts.player",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_players",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "player")},
            },
        ),
    ]
